### PR TITLE
Add support for custom queries.

### PR DESCRIPTION
**Pull request by jmdobry**

### CODE REVIEW

**Comment by jmdobry** [comment]
Needs tests

**Comment by techniq** [comment]
@jmdobry I added some tests and our test coverage went down.  Looking at the [coveralls](https://coveralls.io/builds/3941428/source?filename=dist%2Fjs-data-sql.js) report confuses me :(

**Comment by jmdobry** [comment]
This [`.only`](https://github.com/js-data/js-data-sql/blob/f6d9ed0fcee26a0308e5276a0b69d36a3f62f0f2/test/filterQuery.spec.js#L1) might be why, only 6 of the tests actually ran.

**Comment by techniq** [comment]
Doh. I'll fixed that in the morning

**Comment by techniq** [comment]
Fixed and squashed the branch

**Pull request merged**
