### PR TITLE
Avoid loading belongsTo relations with falsey ids

### PR DESCRIPTION
**Pull request by robertdp**

### CODE REVIEW

**Comment by jmdobry** [comment]
Should it be a falsey check? Or check for `undefined` instead?

**Comment by jmdobry** [comment]
Also, I think pull requests are supposed to go to the `develop` branch.

**Comment by robertdp** [comment]
With SQL, local keys for optional relations will most likely be `null`, not `undefined`, which results in the query:
```
SELECT * FROM table WHERE id = ''
```

> pull requests are supposed to go to the develop branch
Ah, okay. I can make that change if necessary.

**Comment by robertdp** [comment]
Also, the falsey check is already being used for all the other relations, just not `belongsTo`. Which is why only optional `belongsTo` relations are causing `Not Found!` errors to be thrown unnecessarily all over my app.

**Comment by robertdp** [comment]
Moved to https://github.com/js-data/js-data-sql/pull/52

**Pull request closed without merging**
