### PR TITLE
Support filtering across relations (apply joins / fix column name). Fixes #18

### LINKED ISSUE #18: Filter across relation (joins)
It would be very useful if you could apply a join and filter across the join .  For example, with the following resources I want to find all the races at a specific address:

```js
exports.Race = db.store.defineResource({
  name: 'race',
  relations: {
    belongsTo: {
      address: {
        localField: 'address',
        localKey: 'address_id'
      }
    },
  }
});

exports.Address = db.store.defineResource({
  name: 'address',
  relations: {
    hasMany: {
      race: {
        localField: 'races',
        foreignKey: 'address_id'
      }
    }
  }
});
```

Executing `sqlAdapter.findAll(models.Race, { "address.city": "New York" });` would produce:
```sql
select * from race
join address ON race.address_id = address.id AND address.city = 'New York'
```

The equivalent knex query would be:
```js
knex.select('*').from('race').join('address', function() {
  this.on('address.id', '=', 'race.address_id').on('address.city', '=', knex.raw('?', ['New York']))
})
```

### PR DESCRIPTION
**Pull request by techniq**

### CODE REVIEW

**Comment by jmdobry** [comment]
I've got hand it to you, I'm impressed you waded through that gnarly relations code and refactored it. :clap: 

One thing, can you squash your commits into a single commit?

**Comment by techniq** [comment]
Squashed.  I wasn't sure how verbose you wanted the commit message (I left the individual commit messages in the squashed commit).

No worries on the code, I used it as a learning exercise :grinning: 

This PR only supports simple filtering (basically a single "foreign property" can be specified).  If we need to support more complex filtering, we probably need to look at creating aliases on the joined tables and keeping track of what we've joined against already.

I'm might try to knock out filtering within the same chain of relations.  For example:
```js
var comments = yield adapter.findAll(Comment, { 'user.name': 'John' , 'user.profile.email': 'foo@test.com'})
```

Right now js-data-sql creates a join from `comment > user` for the first filter, then does the same for `comment > user > profile` which errors with `ER_NONUNIQ_TABLE: Not unique table/alias: 'user`.

I'll send this improvement as a separate PR when I get time :grinning:

**Comment by techniq** [comment]
Disregard the comment about filtering within the same chain of relations, I implemented that and amended this PR :grinning:

**Comment by jmdobry** [comment]
I'll cut a release tonight.

**Comment by techniq** [comment]
:+1:

**Pull request merged**
